class CustomError(Exception):
    pass


raise CustomError("This is custom defined exception")
